import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

// for making transactions


export default function Home() {
	const [isNetworkSwitchHighlighted, setIsNetworkSwitchHighlighted] =
		useState(false);
	const [isConnectHighlighted, setIsConnectHighlighted] = useState(false);
	const [isMinting, setIsMinting] = useState(false);
	const [showAIimage, setshowAIimage] = useState(false); 

	const closeAll = () => {
		setIsNetworkSwitchHighlighted(false);
		setIsConnectHighlighted(false);
	};

	async function mint() {
		try {
			setIsMinting(true);
		} catch (e) {
			console.log(e);
		}
	}
	function share_with_lens() {
		// share with lens... future integration
	}

	function refresh_metadata() {
		// check for ai image and if available save under /public/ai-image.jpg & then display
		setshowAIimage(true);
	}

	return (
		<>
			<Head>
				<title>Prompt To Chain | Generative AI Minitng Platform</title>
				<meta
					name="Mint your generative AI prompts directly onchain!"
					content="Generated by Lorenz Lehmann"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<div
					className={styles.backdrop}
					style={{
						opacity:
							isConnectHighlighted || isNetworkSwitchHighlighted
								? 1
								: 0,
					}}
				/>
				<div className={styles.header}>
					<div className={styles.logo}>
						<Image
							src="/promt-to-chain.png"
							alt="WalletConnect Logo"
							height={32}
							width={203}
						/>
					</div>
					<div className={styles.buttons}>
						<div
							onClick={closeAll}
							className={`${styles.highlight} ${
								isNetworkSwitchHighlighted
									? styles.highlightSelected
									: ``
							}`}
						>
							<w3m-network-button />
						</div>
						<div
							onClick={closeAll}
							className={`${styles.highlight} ${
								isConnectHighlighted
									? styles.highlightSelected
									: ``
							}`}
						>
							<w3m-button />
						</div>
					</div>
				</div>
			</header>
			<main className={styles.main}>
				<div className={styles.wrapper}>
					<div className={styles.container}>
						<h1>Prompt to Chain!</h1>
						<div className={styles.content}>
							<div className={styles.inputContainer}>
								<input
									type="text"
									className={`${styles.textBox} ${styles.customTextBox}`}
									placeholder="Enter prompt here"
								/>
								<button
									className={`${styles.button} ${styles.customButton} ${styles.biggerButton} ${styles.buttonMargin}`}
									onClick={mint}
								>
									Mint
								</button>
							</div>
							{isMinting && (
								<div>
									<div className={styles.loadingContainer}>
										image is being generated please wait...
									</div>
									<button
										className={`${styles.button} ${styles.customButton} ${styles.biggerButton} ${styles.buttonMargin}`}
										onClick={refresh_metadata}
									>
										refresh metadata
									</button>
								</div>
							)}
							{showAIimage && (
								<div>
									<div className={styles.loadingContainer}>
										<Image
											src="/ai-image.jpg"
											alt="AI Image generated"
											width={1024 / 3}
											height={1024 / 3}
											className="ai-image"
										/>
									</div>
									<div>
										<a href="https://sepolia.scrollscan.dev/address/0xa4a702e8ce5959485c7930cc84f3dc4468006d66" className={styles.link}>
											Check Blockexplorer
										</a>
									</div>
									<button
										className={`${styles.button} ${styles.customButton} ${styles.biggerButton} ${styles.buttonMargin}`}
										onClick={share_with_lens}
									>
										share to Lens
									</button>
								</div>
							)}
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
